### ISSUE TITLE
Recent update with Docker causing "apis.pledge.enabled" is not allowed

### ISSUE THREAD

**Issue by Erisa** [synzen/MonitoRSS-Clone#23]
Had this runninng in Docker Compose for a while now, the most recent version is erroring with
```
TypeError: Bot config validation failed

"apis.pledge.enabled" is not allowed

    at Object.validate (/app/node_modules/monitorss/src/util/config/schema.js:133:13)
    at exports.set (/app/node_modules/monitorss/src/config.js:318:14)
    at new ClientManager (/app/node_modules/monitorss/src/structs/ClientManager.js:35:19)
    at Object.<anonymous> (/app/bot.js:9:23)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/server.js:6:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
/app/node_modules/monitorss/src/util/config/schema.js:133
      throw new TypeError(`Bot config validation failed\n\n${str}\n`)
```

Some digging led me to find `DRSS_APIS_PLEDGE_ENABLED` but setting it doesn't appear to alleviate the issue and I'm not sure what else to do about it.
Apologies if this is an improper place to report the issue.

**Comment by synzen** [comment]
Thanks for the report. This should be fixed now.

**Comment by Erisa** [comment]
Seems to work now, thanks!
