### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Saper140** [synzen/MonitoRSS-Clone#39]
Hello, I just finished setting up the web version through Docker. I'm getting the following error everytime I add an RSS.

```[2022-11-22 19:55:06.285 +0000] INFO: [W] [0m192.168.1.1 (U: 131155472647585802, Nobody) GET /favicon.ico 304  - 3.749 ms                                                      
[2022-11-22 19:55:06.331 +0000] INFO: [W] [0m192.168.1.1 (U: 131155472647585802, Nobody) GET /api/users/@me 304  - 12.619 ms                                                   
[2022-11-22 19:55:06.334 +0000] INFO: [W] [0m192.168.1.1 (U: 131155472647585802, Nobody) GET /api/config 304  - 4.746 ms                                                       
[2022-11-22 19:55:06.335 +0000] INFO: [W] [0m192.168.1.1 (U: 131155472647585802, Nobody) GET /api/users/@me/guilds 304  - 18.647 ms                                            
[2022-11-22 19:55:06.383 +0000] INFO: [W] [0m192.168.1.1 (U: 131155472647585802, Nobody) GET /api/guilds/397907611959164928/feeds 200  - 21.154 ms                             
[2022-11-22 19:55:06.428 +0000] INFO: [W] [0m192.168.1.1 (U: 131155472647585802, Nobody) GET /api/guilds/397907611959164928/channels 304  - 25.015 ms                          
[2022-11-22 19:55:06.451 +0000] INFO: [W] [0m192.168.1.1 (U: 131155472647585802, Nobody) GET /api/guilds/397907611959164928/roles 304  - 39.084 ms                             
[2022-11-22 19:55:06.452 +0000] INFO: [W] [0m192.168.1.1 (U: 131155472647585802, Nobody) GET /api/guilds/397907611959164928/failrecords 304  - 34.604 ms                       
[2022-11-22 19:55:06.474 +0000] INFO: [W] [0m192.168.1.1 (U: 131155472647585802, Nobody) GET /api/users/@bot 304  - 0.718 ms                                                   
[2022-11-22 19:55:06.496 +0000] INFO: [W] [0m192.168.1.1 (U: 131155472647585802, Nobody) GET /static/media/monitorss-logo.ab98090f1def9186417bd476bb0eda93.svg 304  - 0.332 ms 
[2022-11-22 19:55:06.557 +0000] INFO: [W] [0m192.168.1.1 (U: 131155472647585802, Nobody) GET /static/media/icons.9451d5fee89b51a20f8a.woff2 304  - 0.605 ms                    
[2022-11-22 19:55:06.966 +0000] INFO: [W] [0m192.168.1.1 (U: 131155472647585802, Nobody) GET /static/js/main.2220385a.js.map 200  - 0.896 ms
[2022-11-22 19:57:12.857 +0000] ERROR: [W] [0mCannot read property 'name' of undefined                                                                                         
    TypeError: Cannot read property 'name' of undefined                                                                                                                        
        at Feed.testAndSave (/app/node_modules/monitorss/src/structs/db/Feed.js:417:46)                                                                                        
        at runMicrotasks (<anonymous>)                                                                                                                                         
        at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                                                                    
        at async Object.createFeed (/app/node_modules/monitorss-web/src/services/feed.js:66:3)                                                                                 
        at async createFeed (/app/node_modules/monitorss-web/src/controllers/api/guilds/feeds/createFeed.js:35:21)                                                             
[2022-11-22 19:57:12.860 +0000] INFO: [W] [0m192.168.1.1 (U: 131155472647585802, Nobody) POST /api/guilds/397907611959164928/feeds 500 48 - 328.207 ms```

Any help would be much appreciated

**Comment by synzen** [comment]
Apologies for the late reply. I believe this issue should be resolved by ensuring the bot starts first prior to the web.

Since it's been a while, I will close this issue. Feel free to open it again if you still have this problem.
