### ISSUE TITLE
Error on Client start

### ISSUE THREAD

**Issue by l0g4n1337** [synzen/MonitoRSS-Clone#43]
[2023-02-04 12:28:58.391 +0100] ERROR   : [1] Client start
    TypeError: type is undefined
        at new Blacklist (/home/container/node_modules/monitorss/src/structs/db/Blacklist.js:18:13)
        at /home/container/node_modules/monitorss/src/structs/db/Base.js:354:35
        at Array.map (<anonymous>)
        at Function.getAll (/home/container/node_modules/monitorss/src/structs/db/Base.js:354:24)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async Function.initialize (/home/container/node_modules/monitorss/src/structs/Command.js:157:46)
        at async Object.setupCommands (/home/container/node_modules/monitorss/src/initialization/setupCommands.js:6:3)
        at async Client.start (/home/container/node_modules/monitorss/src/structs/Client.js:302:7)
[2023-02-04 12:28:58.407 +0100] ERROR   : [0] Client start
    TypeError: type is undefined
        at new Blacklist (/home/container/node_modules/monitorss/src/structs/db/Blacklist.js:18:13)
        at /home/container/node_modules/monitorss/src/structs/db/Base.js:354:35
        at Array.map (<anonymous>)
        at Function.getAll (/home/container/node_modules/monitorss/src/structs/db/Base.js:354:24)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async Function.initialize (/home/container/node_modules/monitorss/src/structs/Command.js:157:46)
        at async Object.setupCommands (/home/container/node_modules/monitorss/src/initialization/setupCommands.js:6:3)
        at async Client.start (/home/container/node_modules/monitorss/src/structs/Client.js:302:7)

**Comment by synzen** [comment]
Apologies for the late reply - this seems like it may be due to some incomplete data within MongoDB. If you have anything stored in the `blacklists` collection, please delete those documents.

Since it's been a while, I will close this issue. Feel free to open it again if you still have this problem.
