### ISSUE TITLE
Web bot not compatible with file database ?

### ISSUE THREAD

**Issue by AxelTerizaki** [synzen/MonitoRSS-Clone#8]
Hello.

I managed to install the bot without mongodb (I can't use it on my server) and it works well, thanks for that.

However, I'm having trouble with the management interface, even with the same database URI (a directory), it seems to want to connect through mongoDB.

Here's the error I get : 

```
# node bot-web.js
[2020-06-21 15:06:00.971 +0200] INFO : [W] Attempting to connect to databases...
[2020-06-21 15:06:00.975 +0200] ERROR (MongoParseError): [W] WebClientManager failed to start
    MongoParseError: Invalid connection string
        at parseConnectionString (/usr/local/Discord.RSS-Clone/node_modules/mongodb/lib/core/uri_parser.js:547:21)
        at connect (/usr/local/Discord.RSS-Clone/node_modules/mongodb/lib/operations/connect.js:272:3)
        at /usr/local/Discord.RSS-Clone/node_modules/mongodb/lib/mongo_client.js:218:5
        at maybePromise (/usr/local/Discord.RSS-Clone/node_modules/mongodb/lib/utils.js:719:3)
        at MongoClient.connect (/usr/local/Discord.RSS-Clone/node_modules/mongodb/lib/mongo_client.js:214:10)
        at /usr/local/Discord.RSS-Clone/node_modules/mongoose/lib/connection.js:712:12
        at new Promise (<anonymous>)
        at NativeConnection.Connection.openUri (/usr/local/Discord.RSS-Clone/node_modules/mongoose/lib/connection.js:709:19)
        at Mongoose.createConnection (/usr/local/Discord.RSS-Clone/node_modules/mongoose/lib/index.js:279:17)
        at module.exports (/usr/local/Discord.RSS-Clone/node_modules/discord.rss-web/src/util/connectMongo.js:33:30)
        at WebClientManager.start (/usr/local/Discord.RSS-Clone/node_modules/discord.rss-web/src/bot/WebClientManager.js:45:36)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

My config : 

```
  "database": {
    "uri": "/var/lib/Discord.RSS-bot",
    "connection": {},
    "redis": "redis://localhost"
  },
```

Any hope to fix that?

Thanks in advance

**Comment by synzen** [comment]
Hi, as of right now MongoDB is required for the web as the docs indicate:
![image](https://user-images.githubusercontent.com/18688793/85227923-42864a80-b3ae-11ea-8c15-4eece1c0951c.png)

But given that these requirementswere placed before the recent major release v6, the rewrites might be able to make Mongo optional for the web as it is for the bot. I can look into it when I get the chance and get back to you

**Comment by AxelTerizaki** [comment]
Oh my, indeed, I didn't see that one. I assumed since the bot part was compatible with the file db, the web part was as well.

No hurry needed, the bot is usable without the interface at least. :)

**Comment by synzen** [comment]
A file-based database will no longer be an option with the next major release of the bot due to scalability, and the maintenance that goes with it
